import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { AttributionLog } from '../components/AttributionLog';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased">
          <AttributionLog />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
